//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutPacker.Content
{
    
    [NutPackerLib.OriginalNameAttribute("Adventure girl")]
    public class AdventureGirl : NutPacker.ISpriteGroup
    {
        [NutPackerLib.OriginalNameAttribute("Dead")]
        public class Dead : NutPacker.ISpriteSheet
        {
            private static Microsoft.Xna.Framework.Rectangle[] Frames = new Microsoft.Xna.Framework.Rectangle[] {
                    new Microsoft.Xna.Framework.Rectangle(4494, 2715, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(6212, 1086, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(5136, 2172, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(5778, 1691, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(5100, 2777, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(5742, 2296, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(6384, 1691, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(5706, 2901, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(6348, 2296, 605, 604),
                    new Microsoft.Xna.Framework.Rectangle(6312, 2901, 605, 604)};
            public int Length
            {
                get
                {
                    return 10;
                }
            }
            public Microsoft.Xna.Framework.Rectangle this[int index]
            {
                get
                {
                    return Frames[index];
                }
            }
        }
        [NutPackerLib.OriginalNameAttribute("Idle")]
        public class Idle : NutPacker.ISpriteSheet
        {
            private static Microsoft.Xna.Framework.Rectangle[] Frames = new Microsoft.Xna.Framework.Rectangle[] {
                    new Microsoft.Xna.Framework.Rectangle(0, 1144, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(642, 1144, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(1284, 1144, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3002, 1025, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(0, 1687, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(0, 2230, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(642, 1687, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(0, 2773, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(642, 2230, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(1284, 1687, 641, 542)};
            public int Length
            {
                get
                {
                    return 10;
                }
            }
            public Microsoft.Xna.Framework.Rectangle this[int index]
            {
                get
                {
                    return Frames[index];
                }
            }
        }
        [NutPackerLib.OriginalNameAttribute("Jump")]
        public class Jump : NutPacker.ISpriteSheet
        {
            private static Microsoft.Xna.Framework.Rectangle[] Frames = new Microsoft.Xna.Framework.Rectangle[] {
                    new Microsoft.Xna.Framework.Rectangle(642, 2773, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(1284, 2230, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(1926, 2026, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(1284, 2773, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(1926, 2569, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3002, 1568, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(1926, 3112, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(2568, 2111, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(2568, 2654, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3210, 2111, 641, 542)};
            public int Length
            {
                get
                {
                    return 10;
                }
            }
            public Microsoft.Xna.Framework.Rectangle this[int index]
            {
                get
                {
                    return Frames[index];
                }
            }
        }
        [NutPackerLib.OriginalNameAttribute("Melee")]
        public class Melee : NutPacker.ISpriteSheet
        {
            private static Microsoft.Xna.Framework.Rectangle[] Frames = new Microsoft.Xna.Framework.Rectangle[] {
                    new Microsoft.Xna.Framework.Rectangle(2568, 3197, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3210, 2654, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3210, 3197, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3826, 0, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3826, 543, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(4468, 0, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3644, 1086, 641, 542)};
            public int Length
            {
                get
                {
                    return 7;
                }
            }
            public Microsoft.Xna.Framework.Rectangle this[int index]
            {
                get
                {
                    return Frames[index];
                }
            }
        }
        [NutPackerLib.OriginalNameAttribute("Run")]
        public class Run : NutPacker.ISpriteSheet
        {
            private static Microsoft.Xna.Framework.Rectangle[] Frames = new Microsoft.Xna.Framework.Rectangle[] {
                    new Microsoft.Xna.Framework.Rectangle(4468, 543, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(5110, 0, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(4286, 1086, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(5110, 543, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(5752, 0, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3852, 1629, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(4928, 1086, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(3852, 2172, 641, 542)};
            public int Length
            {
                get
                {
                    return 8;
                }
            }
            public Microsoft.Xna.Framework.Rectangle this[int index]
            {
                get
                {
                    return Frames[index];
                }
            }
        }
        [NutPackerLib.OriginalNameAttribute("Shoot")]
        public class Shoot : NutPacker.ISpriteSheet
        {
            private static Microsoft.Xna.Framework.Rectangle[] Frames = new Microsoft.Xna.Framework.Rectangle[] {
                    new Microsoft.Xna.Framework.Rectangle(4494, 1629, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(5752, 543, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(6394, 0, 641, 542)};
            public int Length
            {
                get
                {
                    return 3;
                }
            }
            public Microsoft.Xna.Framework.Rectangle this[int index]
            {
                get
                {
                    return Frames[index];
                }
            }
        }
        [NutPackerLib.OriginalNameAttribute("Slide")]
        public class Slide : NutPacker.ISpriteSheet
        {
            private static Microsoft.Xna.Framework.Rectangle[] Frames = new Microsoft.Xna.Framework.Rectangle[] {
                    new Microsoft.Xna.Framework.Rectangle(3852, 2715, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(5570, 1086, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(4494, 2172, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(5136, 1629, 641, 542),
                    new Microsoft.Xna.Framework.Rectangle(6394, 543, 641, 542)};
            public int Length
            {
                get
                {
                    return 5;
                }
            }
            public Microsoft.Xna.Framework.Rectangle this[int index]
            {
                get
                {
                    return Frames[index];
                }
            }
        }
    }
    [NutPackerLib.OriginalNameAttribute("Graveyard")]
    public class Graveyard : NutPacker.ITileSet
    {
        [NutPackerLib.OriginalNameAttribute("Objects")]
        public class Objects : NutPacker.ITileSet
        {
            [NutPackerLib.OriginalNameAttribute("ArrowSign.png")]
            public static Microsoft.Xna.Framework.Rectangle ArrowSign
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1285, 3445, 86, 87);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Bush (1).png")]
            public static Microsoft.Xna.Framework.Rectangle Bush_1_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(0, 3556, 182, 90);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Bush (2).png")]
            public static Microsoft.Xna.Framework.Rectangle Bush_2_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(183, 3556, 100, 64);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Crate.png")]
            public static Microsoft.Xna.Framework.Rectangle Crate
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(262, 3650, 106, 106);
                }
            }
            [NutPackerLib.OriginalNameAttribute("DeadBush.png")]
            public static Microsoft.Xna.Framework.Rectangle DeadBush
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(0, 3647, 132, 74);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Sign.png")]
            public static Microsoft.Xna.Framework.Rectangle Sign
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(369, 3650, 91, 93);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Skeleton.png")]
            public static Microsoft.Xna.Framework.Rectangle Skeleton
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(0, 3722, 102, 50);
                }
            }
            [NutPackerLib.OriginalNameAttribute("TombStone (1).png")]
            public static Microsoft.Xna.Framework.Rectangle TombStone_1_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1926, 1144, 54, 55);
                }
            }
            [NutPackerLib.OriginalNameAttribute("TombStone (2).png")]
            public static Microsoft.Xna.Framework.Rectangle TombStone_2_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1926, 1200, 53, 76);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tree.png")]
            public static Microsoft.Xna.Framework.Rectangle Tree
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(0, 3316, 286, 239);
                }
            }
        }
        [NutPackerLib.OriginalNameAttribute("Tiles")]
        public class Tiles : NutPacker.ITileSet
        {
            [NutPackerLib.OriginalNameAttribute("BG.png")]
            public static Microsoft.Xna.Framework.Rectangle BG
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(0, 0, 2000, 1143);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Bones (1).png")]
            public static Microsoft.Xna.Framework.Rectangle Bones_1_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(133, 3647, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Bones (2).png")]
            public static Microsoft.Xna.Framework.Rectangle Bones_2_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(511, 3316, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Bones (3).png")]
            public static Microsoft.Xna.Framework.Rectangle Bones_3_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(511, 3445, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Bones (4).png")]
            public static Microsoft.Xna.Framework.Rectangle Bones_4_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(640, 3316, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (1).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_1_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(511, 3574, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (10).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_10_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(640, 3445, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (11).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_11_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(769, 3316, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (12).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_12_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(769, 3445, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (13).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_13_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(898, 3316, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (14).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_14_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(640, 3574, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (15).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_15_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(898, 3445, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (16).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_16_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(769, 3574, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (2).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_2_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1027, 3316, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (3).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_3_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1156, 3316, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (4).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_4_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(898, 3574, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (5).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_5_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1027, 3445, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (6).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_6_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1156, 3445, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (7).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_7_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1027, 3574, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (8).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_8_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1285, 3316, 128, 128);
                }
            }
            [NutPackerLib.OriginalNameAttribute("Tile (9).png")]
            public static Microsoft.Xna.Framework.Rectangle Tile_9_
            {
                get
                {
                    return new Microsoft.Xna.Framework.Rectangle(1156, 3574, 128, 128);
                }
            }
        }
    }
    [NutPackerLib.OriginalNameAttribute("Logo")]
    public class Logo : NutPacker.ITileSet
    {
        [NutPackerLib.OriginalNameAttribute("61004.png")]
        public static Microsoft.Xna.Framework.Rectangle _61004
        {
            get
            {
                return new Microsoft.Xna.Framework.Rectangle(3852, 3258, 510, 510);
            }
        }
        [NutPackerLib.OriginalNameAttribute("cat.png")]
        public static Microsoft.Xna.Framework.Rectangle Cat
        {
            get
            {
                return new Microsoft.Xna.Framework.Rectangle(287, 3316, 223, 333);
            }
        }
        [NutPackerLib.OriginalNameAttribute("google.png")]
        public static Microsoft.Xna.Framework.Rectangle Google
        {
            get
            {
                return new Microsoft.Xna.Framework.Rectangle(2001, 1025, 1000, 1000);
            }
        }
        [NutPackerLib.OriginalNameAttribute("Mozilla_Mascot.jpg")]
        public static Microsoft.Xna.Framework.Rectangle Mozilla_Mascot
        {
            get
            {
                return new Microsoft.Xna.Framework.Rectangle(2001, 0, 1824, 1024);
            }
        }
    }
}
